version: '2'
services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    build: kibana/
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_USERNAME:
      ELASTICSEARCH_PASSWORD:
    depends_on:
      - elasticsearch
volumes:
  elasticsearch:
